(()=>{'use strict';
const app=document.getElementById('app'),P=n=>String(n).padStart(2,'0');
const DAY=[[2,3,2,4,2,2,5],[2,2,2,3,3,2],[4,3,3,4,2,3,3],[4,3,3,3,3,5,1],[4,2,3,2,4,3],[3,3,2,2,2],[2,2,3,1,1],[3,1,2,3,1],[3,1,2,2,2,3],[1,3,2,2,2,2],[3,3,3,4],[5,2,3,4,1,2],[3,1,4,2,3,1],[2,1,2,2,5,3],[3,2,4,3,2,5,3],[4,2,3,3,2,2,3],[3,3,3,2,5,5,3,3],[4,3,4,3,3,2,3,3],[1,2,3,1],[3,1,2,3,2,3],[4,1,2,2],[3,3,5,3,3,2]];
const DQDRIVE={
21:{root:'1_2ErRR1c3vNwBHNu10UeDbcaEbt2R5MW',q:['1HXHVhIB7X3CXWGIrcuyMLygM-Tqlqeog','1kW4g8mkYOeBZ1PpkOUZ-zBrxWK4JRqPo','1PMuAKsLHM2XTyJ4S1aqTmkrOUgJ4VnXm','1ds4xP_Bg23EKT1m8besqkGLaODBIToEl','1msJdfdVFNAh_ax48pBo_ifwjFNkGUqRw'],m:['1jJ47XziyGMUlDBi2Rc9MfwckzfiLGV66','1RiW1GEViyW_pm1TbGrTAkWrDCfgi_Jrn','1pVdY5rUjgdmGwJTa3ecINa5y1fIsx1FF','1CD1DJoAk0orWugTsEfhyqjzuBIvyRUJ8','11PacLC1uj1fSf7Q9fA0_YtPQRvfOL8qC']},
22:{root:'1WNGywDDALeUU2h7RI3smVzk931Zn6FIv',q:['11HMHVEL8iQ66QbYytqwoUeF7Ri5OP_BT','154RQqCTxXSQZfb_WIYPryPq4LMIyBR5c','1FOJWJ39ahecbK0leWB9-lUYwYCFjJPcq','1gyRomGMUk5IXRuuXSn2-viA3a9ZdhvKg','1-xZPrpaZWcxn-qwSqrQVkea-XpqhoqaM'],m:['1X7Xl6o915pUUgGoYsFusyjPVrOf3lyrT','1rCvZZDe5qWg-rc8pQPf8QGB-FBpRcqLv','1hpfzADbn4wRJ-393FBWisIxkU6eGdXJ-','1kvhpCcZJ5ND5uaBiJ-8u_BS5shAURwPy','1NgR6r3YkEPWYj_M9Yjkm2uco12t8aWW6']},
23:{root:'1dsZcoxEdkHcUSCBGMGP6xm-JSjSlvESw',q:['1XBfARptKgUVjean8fb3qqj69DJ63jbLO','16G4xm12zk8ShJ1HQ9psdri5xXbjTzPQR','1UHNuuR6lZtLZ5MRzCLOL-8sxxQfrqAuD','17Vr390DCgIgtmpLOYBuyh3nT1ke5Un2N','1GV5i4XTbcD4cNvWMDV5Q6VAeV-RQsO61'],m:['1iurD264mNRSi2MfJaILQkjETV0WXWgjg','1VX5NaUTRGBPJUp8hlJiMaguPY5gPNBWI','1DbAzxMx-EDdlbC4tzVizM1Q7B22ErLZR','16JQApiNlNypeexDxe1DPczU8MC1BGtV-','13YtFuplACtfnFIHDDvtkZY_fW4lJEfnH']}
};
const Q14M2='1SmLjCwuF9d2vf8R2PUilVTMTxQwE-Gvr';
let BANK=[],session=[],ix=0,picks={},label='';
const saved=new Set(JSON.parse(localStorage.getItem('ict347saved')||'[]'));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const shuffle=a=>[...a].sort(()=>Math.random()-.5),store=()=>localStorage.setItem('ict347saved',JSON.stringify([...saved]));
const dprev=id=>`https://drive.google.com/file/d/${id}/preview`,dview=id=>`https://drive.google.com/file/d/${id}/view`;
const driveId=u=>{let m=String(u||'').match(/drive\.google\.com\/file\/d\/([A-Za-z0-9_-]+)/);return m?m[1]:''};
function localLessonSource(raw,pageHint){let s=String(raw||''),id=driveId(s);if(!id)return s;let pm=s.match(/#page=(\d+)/),page=pageHint||pm&&pm[1];return`sources/${id}.pdf${page?`#page=${page}`:''}`}
function resourceHref(r){let raw=r&&String(r.previewUrl||r.sourceUrl||r.url||''),id=r&&(r.driveId||driveId(raw));if(id){let pm=raw.match(/#page=(\d+)/),page=r.page||pm&&pm[1];return`sources/${id}.pdf${page?`#page=${page}`:''}`}return raw&&!/drive\.google\.com/i.test(raw)?raw:''}
async function init(){try{let r=await fetch('quiz-data.json',{cache:'no-store'});if(!r.ok)throw new Error(r.status);let dq=await r.json();BANK=[...makeDay(),...makeDaily(dq.answers||[]),...makePast()];if(BANK.length!==347)throw new Error(`bank ${BANK.length}`);home()}catch(e){app.innerHTML=`<main class="results"><div class="result-card"><h1>Source data failed to load</h1><p>${esc(e.message)}. No fallback questions were generated.</p></div></main>`}}
function makeDay(){return DAY.flatMap((a,i)=>a.map((ans,j)=>{let q=i+1,n=j+1,ext=q===22?'jpg':'webp',base='https://ict-day-papers-cropped.vercel.app/assets';return{id:`DAY-${P(q)}-${P(n)}`,source:'Day Paper',sourceKey:`PHY ${P(q)}`,n,answer:ans,question:`${base}/questions/phy-${P(q)}/q-${P(n)}.${ext}`,marking:`${base}/markings/phy-${P(q)}/q-${P(n)}.${ext}`,sourceUrl:'https://ict-day-papers-cropped.vercel.app/'}}))}
function makeDaily(rows){return rows.flatMap((a,i)=>a.map((ans,j)=>{let q=i+1,n=j+1,d=DQDRIVE[q],o={id:`DQ-${P(q)}-${P(n)}`,source:'Daily Quiz',sourceKey:`Quiz ${P(q)}`,n,answer:ans};if(d){o.question=dprev(d.q[j]);o.marking=dprev(d.m[j]);o.drive=true;o.sourceUrl=`https://drive.google.com/drive/folders/${d.root}`}else{o.question=`daily_assets/questions/quiz-${P(q)}/q-${P(n)}.webp`;o.marking=q===14&&n===2?dprev(Q14M2):`daily_assets/markings/quiz-${P(q)}/q-${P(n)}.webp`;o.markingDrive=q===14&&n===2;o.sourceUrl=q===14&&n===2?dview(Q14M2):''}return o}))}
function makePast(){let src=window.SOURCE_QUIZ_DATA||{},out=[];(src.mcq||[]).forEach(x=>{let n=x.lesson===1&&x.n>=35?x.n+1:x.n,u=localLessonSource(x.previewUrl||x.sourceUrl,x.page);out.push({id:`PP-L${x.lesson}-${P(n)}`,source:'Past Paper',sourceKey:`Lesson ${x.lesson} Past Papers`,lesson:x.lesson,n,answer:x.answer,previewUrl:u,sourceUrl:u,year:x.year,paperQuestion:x.paperQuestion})});let u='sources/1f3DpT3-qcBpEjIRf8CqXK1j4pRd3ObwL.pdf';out.push({id:'PP-L1-35',source:'Past Paper',sourceKey:'Lesson 1 Past Papers',lesson:1,n:35,answer:null,previewUrl:u,sourceUrl:u});return out.sort((a,b)=>a.lesson-b.lesson||a.n-b.n)}
function home(){let c={day:BANK.filter(x=>x.source==='Day Paper').length,daily:BANK.filter(x=>x.source==='Daily Quiz').length,past:BANK.filter(x=>x.source==='Past Paper').length};app.innerHTML=`<main class="home"><div class="wrap"><header class="header"><div class="brand"><div class="brand-badge">ICT</div><div><strong>Source Quiz Studio</strong><small>LESSON 1 + LESSON 2</small></div></div><div class="pill">SOURCE LOCKED • NO AI QUESTIONS</div></header><section class="hero"><div><div class="eyebrow">Verified source practice</div><h1>Study the source.<span>Master every pattern.</span></h1><p class="lead">Day Papers, Daily Quiz and Lesson 1–2 Past Papers in one practice flow. Source question → your answer → original marking/source.</p><div class="actions"><button class="btn primary" data-m="mix">Start 20Q Mixed</button><button class="btn secondary" id="bank">Question Bank</button><button class="btn secondary" id="res">Essay + Theory</button></div><div class="stats"><div><strong>${BANK.length}</strong><span>MCQ INSTANCES</span></div><div><strong>${c.day}</strong><span>DAY PAPERS</span></div><div><strong>${c.daily}</strong><span>DAILY QUIZ</span></div><div><strong>${c.past}</strong><span>PAST PAPERS</span></div></div></div><div class="demo"><div class="demo-top"><span>ORIGINAL SOURCE</span><span>MARKING REVEAL</span></div><div class="track"><i></i></div><div class="mini">SOURCE-LOCKED</div><h2>Answer, then learn.</h2><div class="answers-preview"><span>1</span><span>2</span><span class="on">3</span><span>4</span><span>5</span></div><div class="demo-ok"><b>✓</b><div><strong>Original marking shown next</strong><small>No rewritten explanation.</small></div></div></div></section><section class="papers"><div class="section-head"><div><div class="eyebrow">Practice modes</div><h2>Choose your bank</h2></div></div><div class="paper-grid">${card('day','Day Papers',`${c.day} questions`)}${card('daily','Daily Quiz',`${c.daily} questions`)}${card('l1','Lesson 1 Past Papers','44 questions')}${card('l2','Lesson 2 Past Papers','56 questions')}${card('mix','Mixed Mock','20 random questions')}${card('saved','Saved Review',`${saved.size} saved`)}</div></section><footer class="footer"><span>ICT Lesson 1 + 2</span><span>Original source material preserved.</span></footer></div></main>`;document.querySelectorAll('[data-m]').forEach(b=>b.onclick=()=>start(b.dataset.m));document.getElementById('bank').onclick=library;document.getElementById('res').onclick=resources}
function card(m,t,s){return`<button class="paper-card" data-m="${m}"><div class="paper-top"><span class="paper-number">${t[0]}</span><span class="paper-count">${esc(s)}</span></div><h3>${esc(t)}</h3><div class="paper-progress"><i style="width:100%"></i></div><div class="paper-foot"><span>Source practice</span><span>→</span></div></button>`}
function pickSet(m){if(m==='day')return BANK.filter(x=>x.source==='Day Paper');if(m==='daily')return BANK.filter(x=>x.source==='Daily Quiz');if(m==='l1')return BANK.filter(x=>x.source==='Past Paper'&&x.lesson===1);if(m==='l2')return BANK.filter(x=>x.source==='Past Paper'&&x.lesson===2);if(m==='saved')return BANK.filter(x=>saved.has(x.id));return shuffle(BANK).slice(0,20)}
function start(m){session=pickSet(m);if(!session.length)return alert('No questions in this set.');label={day:'Day Papers',daily:'Daily Quiz',l1:'Lesson 1 Past Papers',l2:'Lesson 2 Past Papers',mix:'20Q Mixed Mock',saved:'Saved Review'}[m];ix=0;picks={};question()}
function media(src,title,q,forceFrame=false){let frame=forceFrame||/\.pdf(?:#|$)/i.test(src||'')||/drive\.google\.com\/file\//.test(src||'');return`<div class="pdf-card"><div class="pdf-head"><strong>${esc(title)}</strong>${q.sourceUrl?`<a class="source-link" target="_blank" rel="noopener" href="${esc(q.sourceUrl)}">Open source ↗</a>`:''}</div>${frame?`<iframe class="source-frame" loading="lazy" src="${esc(src)}" title="${esc(title)}"></iframe>`:`<img class="source-img" src="${esc(src)}" alt="${esc(title)}">`}</div>`}
function sourceView(q){if(q.source==='Past Paper')return media(q.previewUrl,'Original question source',q,true);return media(q.question,'Original question crop',q,q.drive)}
function markingView(q){if(q.source==='Past Paper')return media(q.previewUrl,'Original source / marking page',q,true);return media(q.marking,'Original marking crop',q,q.drive||q.markingDrive)}
function question(){let q=session[ix],p=picks[q.id],pct=(ix+1)/session.length*100;app.innerHTML=`<main class="quiz"><header class="quiz-header"><button class="icon" id="back">←</button><div class="qtitle"><small>${esc(label).toUpperCase()}</small><strong>${esc(q.sourceKey)} • Question ${q.n}</strong></div><button class="save ${saved.has(q.id)?'on':''}" id="save">${saved.has(q.id)?'★':'☆'} Save</button><div class="counter">${ix+1}/${session.length}</div></header><div class="top-progress"><i style="width:${pct}%"></i></div><section class="stage"><div class="qmeta"><div><div class="qkicker">${esc(q.source)}${q.lesson?` • LESSON ${q.lesson}`:''}</div><h1>${esc(q.sourceKey)} — Q${P(q.n)}</h1>${q.year?`<small>${q.year}${q.paperQuestion?` • Paper Q${q.paperQuestion}`:''}</small>`:''}</div></div>${sourceView(q)}<div class="answer-box"><div class="answer-head"><strong>Select your answer</strong><span>${q.answer==null?'Source item: non-numeric':'Choose 1–5'}</span></div><div class="choices">${[1,2,3,4,5].map(n=>choice(n,p,q.answer)).join('')}</div>${p!=null?feedback(p,q.answer):''}${p!=null?`<div style="margin-top:16px;display:flex;justify-content:flex-end"><button class="btn secondary dark" id="retryOne">↻ Try this question again</button></div>`:''}</div>${p!=null?`<div class="marking"><h2>Original Marking / Source</h2>${markingView(q)}</div>`:''}<div class="nav"><button id="prev" ${ix===0?'disabled':''}>← Previous</button><span>${ix+1} of ${session.length}</span><button class="next" id="next">${ix===session.length-1?'Finish':'Next →'}</button></div></section></main>`;document.getElementById('back').onclick=home;document.getElementById('save').onclick=()=>{saved.has(q.id)?saved.delete(q.id):saved.add(q.id);store();question()};document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{picks[q.id]=+b.dataset.n;question()});let retry=document.getElementById('retryOne');if(retry)retry.onclick=()=>{delete picks[q.id];question()};document.getElementById('prev').onclick=()=>{if(ix){ix--;question()}};document.getElementById('next').onclick=()=>{if(ix<session.length-1){ix++;question()}else results()};document.querySelectorAll('.source-img').forEach(im=>im.onerror=()=>im.outerHTML='<p>Crop failed to load. Use the source view.</p>')}
function choice(n,p,a){let c='choice';if(p!=null){if(a!=null&&n===a)c+=' correct';else if(n===p)c+=' wrong';else c+=' dim'}return`<button class="${c}" data-n="${n}" ${p!=null?'disabled':''}>${n}</button>`}
function feedback(p,a){if(a==null)return`<div class="feedback bad"><div class="mark">i</div><div><strong>Source uses a non-numeric answer</strong><p>Not scored. Read the original source below.</p></div></div>`;let ok=p===a;return`<div class="feedback ${ok?'good':'bad'}"><div class="mark">${ok?'✓':'×'}</div><div><strong>${ok?'Correct':'Not correct'}</strong><p>${ok?'Matches the source answer.':`Source answer: ${a}.`} Read the original marking below.</p></div></div>`}
function results(){let scored=session.filter(q=>q.answer!=null),correct=scored.filter(q=>picks[q.id]===q.answer).length,missed=scored.filter(q=>picks[q.id]!==q.answer),pct=scored.length?Math.round(correct/scored.length*100):0;app.innerHTML=`<main class="results"><div class="result-card"><div class="eyebrow">SESSION COMPLETE</div><h1>${pct}%</h1><div class="score" style="--score:${pct*3.6}deg"><div><strong>${correct}</strong><span>OF ${scored.length}</span></div></div><div class="result-stats"><div><span>ANSWERED</span><strong>${Object.keys(picks).length}</strong></div><div><span>CORRECT</span><strong>${correct}</strong></div><div><span>SAVED</span><strong>${saved.size}</strong></div></div><div class="actions center"><button class="btn primary" id="again">↻ Retry Session</button><button class="btn secondary dark" id="missed" ${missed.length?'':'disabled'}>Retry Missed (${missed.length})</button><button class="btn secondary dark" id="homeBtn">Home</button></div></div></main>`;document.getElementById('again').onclick=()=>{ix=0;picks={};question()};document.getElementById('missed').onclick=()=>{if(!missed.length)return;session=[...missed];label=`${label} • Retry Missed`;ix=0;picks={};question()};document.getElementById('homeBtn').onclick=home}
function library(){app.innerHTML=`<main class="library"><div class="wrap"><div class="subhead"><button class="icon" id="back">←</button><div><small>SOURCE BANK</small><h1>All ${BANK.length} MCQ instances</h1></div></div><div class="filters"><select id="s"><option value="">All sources</option><option>Day Paper</option><option>Daily Quiz</option><option>Past Paper</option></select><select id="l"><option value="">All lessons</option><option value="1">Lesson 1</option><option value="2">Lesson 2</option></select><input id="t" placeholder="Search PHY 10, Quiz 21, PP-L1"><button class="btn secondary dark" id="only">Saved only</button></div><div class="bank-list" id="list"></div></div></main>`;document.getElementById('back').onclick=home;let onlySaved=false,s=document.getElementById('s'),l=document.getElementById('l'),t=document.getElementById('t'),only=document.getElementById('only'),list=document.getElementById('list');['s','l','t'].forEach(id=>document.getElementById(id).oninput=draw);only.onclick=()=>{onlySaved=!onlySaved;draw()};draw();function draw(){let sv=s.value,lv=l.value,tv=t.value.toLowerCase(),a=BANK.filter(q=>(!sv||q.source===sv)&&(!lv||String(q.lesson||'')===lv)&&(!onlySaved||saved.has(q.id))&&(!tv||(`${q.id} ${q.sourceKey}`).toLowerCase().includes(tv)));list.innerHTML=a.map(q=>`<button class="bank-row" data-id="${q.id}"><span>${P(q.n)}</span><span><small>${esc(q.source)}</small><strong>${esc(q.sourceKey)} — ${esc(q.id)}</strong></span><b>${q.answer==null?'SOURCE':`Ans ${q.answer}`}</b></button>`).join('');document.querySelectorAll('.bank-row').forEach(b=>b.onclick=()=>{session=[BANK.find(q=>q.id===b.dataset.id)];label='Source Bank';ix=0;picks={};question()})}}
function resources(){let src=window.SOURCE_QUIZ_DATA||{},e=src.essays||src.essay||[],n=src.notes||src.theory||[],items=[...e.map(r=>({...r,_kind:'ESSAY'})),...n.map(r=>({...r,_kind:'THEORY'}))];app.innerHTML=`<main class="library"><div class="wrap"><div class="subhead"><button class="icon" id="back">←</button><div><small>LESSON 1 + 2</small><h1>Essay + Theory Sources</h1></div></div><div class="library-note"><strong>In-app source mode:</strong> these Lesson 1 + 2 PDFs are served from this Vercel deployment. The reader does not load Google Drive.</div><div class="essay-grid" style="margin-top:18px">${items.map((r,i)=>{let u=resourceHref(r);return`<article class="note-card"><small>${esc(r._kind)} • SOURCE ${i+1}</small><h3>${esc(r.title||`Source ${i+1}`)}</h3>${u?`<button class="source-link" data-res="${i}">View inside app →</button>`:`<span style="color:#b34459;font-weight:800">Local source unavailable</span>`}</article>`}).join('')}</div></div></main>`;document.getElementById('back').onclick=home;document.querySelectorAll('[data-res]').forEach(b=>b.onclick=()=>resourceReader(items[+b.dataset.res],+b.dataset.res+1))}
function resourceReader(r,num){let u=resourceHref(r),title=r.title||`Source ${num}`;app.innerHTML=`<main class="library"><div class="wrap"><div class="subhead"><button class="icon" id="back">←</button><div><small>${esc(r._kind||'SOURCE')} • SOURCE ${num}</small><h1>${esc(title)}</h1></div></div><div class="library-note">Original source • hosted inside the app • no Drive iframe</div>${u?`<div class="pdf-card" style="margin-top:18px"><iframe class="source-frame" loading="eager" src="${esc(u)}" title="${esc(title)}"></iframe></div>`:`<div class="result-card"><h2>Local source unavailable</h2><p>This item was not published into the app build.</p></div>`}</div></main>`;document.getElementById('back').onclick=resources}
init();})();